"""Configuration constants and enumerations for the MCP server."""
from __future__ import annotations

from enum import Enum
from typing import Dict, List


class VulnerabilityClass(str, Enum):
    """Supported vulnerability classes mapped to well known frameworks."""

    # OWASP Top 10 (Web)
    A01_BROKEN_ACCESS_CONTROL = "OWASP_A01_BROKEN_ACCESS_CONTROL"
    A02_CRYPTO_FAILURES = "OWASP_A02_CRYPTOGRAPHIC_FAILURES"
    A03_INJECTION = "OWASP_A03_INJECTION"
    A04_INSECURE_DESIGN = "OWASP_A04_INSECURE_DESIGN"
    A05_SECURITY_MISCONFIG = "OWASP_A05_SECURITY_MISCONFIGURATION"
    A06_VULNERABLE_AND_OUTDATED_COMPONENTS = "OWASP_A06_VULNERABLE_AND_OUTDATED_COMPONENTS"
    A07_IDENT_AND_AUTHN_FAILS = "OWASP_A07_IDENTIFICATION_AND_AUTHENTICATION_FAILURES"
    A08_SOFTWARE_AND_DATA_INTEGRITY = "OWASP_A08_SOFTWARE_AND_DATA_INTEGRITY_FAILURES"
    A09_SECURITY_LOGGING_AND_MONITORING = "OWASP_A09_SECURITY_LOGGING_AND_MONITORING_FAILS"
    A10_SERVER_SIDE_REQUEST_FORGERY = "OWASP_A10_SERVER_SIDE_REQUEST_FORGERY"

    # OWASP Mobile Top 10
    M1_IMPROPER_PLATFORM_USAGE = "OWASP_M1_IMPROPER_PLATFORM_USAGE"
    M2_INSECURE_DATA_STORAGE = "OWASP_M2_INSECURE_DATA_STORAGE"
    M3_INSECURE_COMMUNICATION = "OWASP_M3_INSECURE_COMMUNICATION"
    M4_INSECURE_AUTHENTICATION = "OWASP_M4_INSECURE_AUTHENTICATION"
    M5_INSUFFICIENT_CRYPTOGRAPHY = "OWASP_M5_INSUFFICIENT_CRYPTOGRAPHY"
    M6_INSECURE_AUTHORIZATION = "OWASP_M6_INSECURE_AUTHORIZATION"
    M7_CLIENT_CODE_QUALITY = "OWASP_M7_CLIENT_CODE_QUALITY"
    M8_CODE_TAMPERING = "OWASP_M8_CODE_TAMPERING"
    M9_REVERSE_ENGINEERING = "OWASP_M9_REVERSE_ENGINEERING"
    M10_EXCESSIVE_PRIVILEGES = "OWASP_M10_EXCESSIVE_PRIVILEGES"

    # CWE / SANS Top 25
    CWE_787_OUT_OF_BOUNDS_WRITE = "CWE_787_OUT_OF_BOUNDS_WRITE"
    CWE_79_XSS = "CWE_79_CROSS_SITE_SCRIPTING"
    CWE_89_SQL_INJECTION = "CWE_89_SQL_INJECTION"
    CWE_20_IMPROPER_INPUT_VALIDATION = "CWE_20_IMPROPER_INPUT_VALIDATION"
    CWE_125_OUT_OF_BOUNDS_READ = "CWE_125_OUT_OF_BOUNDS_READ"
    CWE_416_USE_AFTER_FREE = "CWE_416_USE_AFTER_FREE"
    CWE_190_INTEGER_OVERFLOW = "CWE_190_INTEGER_OVERFLOW"
    CWE_352_CSRF = "CWE_352_CROSS_SITE_REQUEST_FORGERY"
    CWE_78_OS_COMMAND_INJECTION = "CWE_78_OS_COMMAND_INJECTION"
    CWE_787_BUFFER_OVERFLOW = "CWE_787_BUFFER_OVERFLOW"


class ScanStatus(str, Enum):
    """Represents the lifecycle state of a scan job."""

    DRAFT = "draft"
    SCHEDULED = "scheduled"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class AgentRole(str, Enum):
    """Functional role performed by an autonomous agent."""

    DECISION_ENGINE = "decision_engine"
    OPERATIONS = "operations"
    ANALYST = "analyst"
    REPORTING = "reporting"


class AgentStatus(str, Enum):
    """Connection and readiness state of an agent."""

    DISCONNECTED = "disconnected"
    CONNECTING = "connecting"
    READY = "ready"
    BUSY = "busy"
    ERROR = "error"


class RiskLevel(str, Enum):
    """Normalized qualitative risk buckets."""

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


DEFAULT_REPORT_SECTIONS: List[str] = [
    "Title",
    "Index",
    "Executive Summary",
    "Scope",
    "Detailed Vulnerabilities",
]


DEFAULT_THRESHOLDS: Dict[str, float] = {
    "max_open_ports": 100.0,
    "max_critical_findings": 5.0,
    "max_high_findings": 15.0,
}
